version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/shift"
    depends_on:
      - db

  tests:
    command: poetry run pytest
    build: .
    environment:
      TZ: Europe/Moscow
      DATABASE_URL: "postgresql://postgres:password@db:5432/tests"
      DATABASE_TEST_URL: "postgresql://postgres:password@db:5432/tests"
      PYTHONPATH: .
    depends_on:
      - db
    volumes:
      - ./htmlcov:/app/htmlcov

  db:
    image: postgres:13
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shift
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-initdb-init:/db-initdb-init:ro
    ports:
      - "5433:5432"

volumes:
  postgres_data:
