version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/shift"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shift
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"

  tests:
    build: .
    command: "poetry run pytest --cov=. --cov-report=html"
    environment:
      TZ: Europe/Moscow
      DATABASE_URL: "postgresql+psycopg2://postgres:password@db:5432/tests"
      PYTHONPATH: .
    depends_on:
      - db
    volumes:
      - ./htmlcov:/app/htmlcov

volumes:
  postgres_data:
